[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
primaryColor = "#ff4757"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "Monospace"
